"""user and College models


Revision ID: 055223727e77
Revises: 
Create Date: 2018-06-27 12:26:29.637614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055223727e77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('room_and_board', sa.Float(precision=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type_of_institution', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('in_state_tuition', sa.Float(precision=2), nullable=True),
    sa.Column('out_of_state_tuition', sa.Float(precision=2), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('in_state_requirement', sa.Text(), nullable=True),
    sa.Column('counties', sa.Text(), nullable=True),
    sa.Column('religious_affiliation', sa.String(length=256), nullable=True),
    sa.Column('setting', sa.String(length=256), nullable=True),
    sa.Column('number_of_students', sa.Integer(), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('majors', sa.Text(), nullable=True),
    sa.Column('campus_photo', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('hits', sa.BigInteger(), nullable=True),
    sa.Column('total_ofs', sa.Float(precision=2), nullable=True),
    sa.Column('total_is', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('college')
    # ### end Alembic commands ###
