"""grade schema

Revision ID: 08a453bfc656
Revises: 6144e902c0fe
Create Date: 2019-03-12 01:27:20.473815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a453bfc656'
down_revision = '6144e902c0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_name'), 'grade', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_name'), table_name='grade')
    op.drop_table('grade')
    # ### end Alembic commands ###
