"""public id for user

Revision ID: 13a694488432
Revises: bddd089de731
Create Date: 2019-02-03 17:40:20.411488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a694488432'
down_revision = 'bddd089de731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
