"""submission schema

Revision ID: 2d504fef79db
Revises: 13a694488432
Create Date: 2019-02-13 20:16:17.912865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d504fef79db'
down_revision = '13a694488432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('college', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('college', 'updated_at')
    op.drop_column('college', 'created_at')
    # ### end Alembic commands ###
