"""backref of scholarships_needed changed to scneeded_by_scholarships

Revision ID: 2dfdf76f6fbd
Revises: 653d45cbd701
Create Date: 2018-08-08 20:45:46.634044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfdf76f6fbd'
down_revision = '653d45cbd701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('college_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.create_foreign_key(None, 'scholarship', 'college', ['college_id'], ['id'])
    op.drop_column('scholarship', 'scholarship_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('scholarship_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.create_foreign_key(None, 'scholarship', 'scholarship', ['scholarship_id'], ['id'])
    op.drop_column('scholarship', 'college_id')
    # ### end Alembic commands ###
