"""initial migration

Revision ID: 2f4940011295
Revises: 
Create Date: 2018-07-20 19:55:23.282084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4940011295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('room_and_board', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type_of_institution', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('in_state_tuition', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('out_of_state_tuition', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('in_state_requirement', sa.Text(), nullable=True),
    sa.Column('counties', sa.Text(), nullable=True),
    sa.Column('religious_affiliation', sa.String(length=256), nullable=True),
    sa.Column('setting', sa.String(length=256), nullable=True),
    sa.Column('number_of_students', sa.Integer(), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('majors', sa.Text(), nullable=True),
    sa.Column('hits', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('scholarship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('act', sa.SmallInteger(), nullable=True),
    sa.Column('sat', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.String(length=256), nullable=True),
    sa.Column('amount_expression', sa.String(length=256), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('class_rank', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('relevant_information', sa.String(length=256), nullable=True),
    sa.Column('national_merit_finalist', sa.Boolean(), nullable=True),
    sa.Column('graduated_spring_before_college', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('counties', sa.Text(), nullable=True),
    sa.Column('not_allowed_counties', sa.Text(), nullable=True),
    sa.Column('not_allowed_locations', sa.Text(), nullable=True),
    sa.Column('governors_scholar_program', sa.Boolean(), nullable=True),
    sa.Column('rogers_scholar_program', sa.Boolean(), nullable=True),
    sa.Column('paid_full_time_christian_ministry_parent', sa.Boolean(), nullable=True),
    sa.Column('parents_higher_education', sa.Boolean(), nullable=True),
    sa.Column('siblings_currently_in_college', sa.Boolean(), nullable=True),
    sa.Column('application_needed', sa.Boolean(), nullable=True),
    sa.Column('scholarships_needed', sa.Text(), nullable=True),
    sa.Column('ethnicity', sa.String(length=256), nullable=True),
    sa.Column('first_choice_national_merit', sa.String(length=256), nullable=True),
    sa.Column('national_hispanic_recognition_scholar', sa.Boolean(), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('group_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholarship')
    op.drop_table('picture')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('college')
    # ### end Alembic commands ###
