"""added observation column

Revision ID: 36cb3ff1e653
Revises: 8b8ded12c7c5
Create Date: 2019-02-21 21:03:23.998127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cb3ff1e653'
down_revision = '8b8ded12c7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('observation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'observation')
    # ### end Alembic commands ###
