"""program name column not unique now

Revision ID: 4f7181060fb5
Revises: fd7ffd6b6585
Create Date: 2018-12-16 18:07:12.920536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7181060fb5'
down_revision = 'fd7ffd6b6585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_name', table_name='program')
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.create_index('ix_program_name', 'program', ['name'], unique=1)
    # ### end Alembic commands ###
