"""College/scholarship relationship backref college

Revision ID: 573daf20e296
Revises: 7acfd160592d
Create Date: 2018-06-27 21:04:01.188708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573daf20e296'
down_revision = '7acfd160592d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('act', sa.SmallInteger(), nullable=True),
    sa.Column('sat', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.String(length=256), nullable=True),
    sa.Column('amount_expression', sa.String(length=256), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('class_rank', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('relevant_information', sa.String(length=256), nullable=True),
    sa.Column('national_merit_finalist', sa.Boolean(), nullable=True),
    sa.Column('graduated_spring_before_college', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('counties', sa.Text(), nullable=True),
    sa.Column('not_allowed_counties', sa.Text(), nullable=True),
    sa.Column('not_allowed_locations', sa.Text(), nullable=True),
    sa.Column('governors_scholar_program', sa.Boolean(), nullable=True),
    sa.Column('rogers_scholar_program', sa.Boolean(), nullable=True),
    sa.Column('paid_full_time_christian_ministry_parent', sa.Boolean(), nullable=True),
    sa.Column('parents_higher_education', sa.Boolean(), nullable=True),
    sa.Column('siblings_currently_in_college', sa.Boolean(), nullable=True),
    sa.Column('application_needed', sa.Boolean(), nullable=True),
    sa.Column('scholarships_needed', sa.Text(), nullable=True),
    sa.Column('ethnicity', sa.String(length=256), nullable=True),
    sa.Column('first_choice_national_merit', sa.String(length=256), nullable=True),
    sa.Column('national_hispanic_recognition_scholar', sa.Boolean(), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('group_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholarship')
    # ### end Alembic commands ###
