"""scholarship and scholarship details

Revision ID: 5bbd636c715f
Revises: 8584bb7e411d
Create Date: 2019-03-09 19:56:04.411888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbd636c715f'
down_revision = '8584bb7e411d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exclude_from_match', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholarship_details',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.String(length=256), nullable=True),
    sa.Column('amount_expression', sa.String(length=256), nullable=True),
    sa.Column('application_needed', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_details_name'), 'scholarship_details', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_details_name'), table_name='scholarship_details')
    op.drop_table('scholarship_details')
    op.drop_table('scholarship')
    # ### end Alembic commands ###
