"""Scholarship model

Revision ID: 5dd808243ed5
Revises: 055223727e77
Create Date: 2018-06-27 19:08:02.407051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd808243ed5'
down_revision = '055223727e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('college', 'total_ofs')
    op.drop_column('college', 'total_is')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college', sa.Column('total_is', sa.FLOAT(), nullable=True))
    op.add_column('college', sa.Column('total_ofs', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
