"""scholarship additional details

Revision ID: 625933f7b1a1
Revises: 5bbd636c715f
Create Date: 2019-03-10 17:34:26.248261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625933f7b1a1'
down_revision = '5bbd636c715f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('scholarship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detail', 'scholarship', ['scholarship_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail', type_='foreignkey')
    op.drop_column('detail', 'scholarship_id')
    # ### end Alembic commands ###
