"""added name column to college_details table

Revision ID: 64aee479ac50
Revises: a3ea3a328d77
Create Date: 2019-03-03 03:16:02.909193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64aee479ac50'
down_revision = 'a3ea3a328d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_college_name', table_name='college')
    op.drop_column('college', 'name')
    op.add_column('college_details', sa.Column('name', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_college_details_name'), 'college_details', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_college_details_name'), table_name='college_details')
    op.drop_column('college_details', 'name')
    op.add_column('college', sa.Column('name', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('ix_college_name', 'college', ['name'], unique=True)
    # ### end Alembic commands ###
