"""college scholarships relationship

Revision ID: 767a3f6a8185
Revises: 8e6a08d1355c
Create Date: 2019-03-14 02:58:03.647086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767a3f6a8185'
down_revision = '8e6a08d1355c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('college_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scholarship', 'college', ['college_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.drop_column('scholarship', 'college_id')
    # ### end Alembic commands ###
