"""Scholarships cascade delete

Revision ID: 7ac9e6ab95a8
Revises: 58a18f57748f
Create Date: 2018-07-17 17:13:27.173552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac9e6ab95a8'
down_revision = '58a18f57748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.create_foreign_key(None, 'scholarship', 'college', ['college_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.create_foreign_key(None, 'scholarship', 'college', ['college_id'], ['id'])
    # ### end Alembic commands ###
