"""detail table

Revision ID: 828938cd15ec
Revises: 911dde1e5a2b
Create Date: 2019-03-05 21:46:58.884403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828938cd15ec'
down_revision = '911dde1e5a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('college_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_details_id'], ['college_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    # ### end Alembic commands ###
