"""programs and qualification rounds

Revision ID: 84b6ead550ad
Revises: e7e3cb7f9f20
Create Date: 2019-03-11 01:04:17.567886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b6ead550ad'
down_revision = 'e7e3cb7f9f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualification_round', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_round', sa.Column('description', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
