"""added additional_details to college

Revision ID: 8584bb7e411d
Revises: 828938cd15ec
Create Date: 2019-03-06 00:26:21.613946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8584bb7e411d'
down_revision = '828938cd15ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('college_id', sa.Integer(), nullable=True))
    op.drop_constraint('detail_ibfk_1', 'detail', type_='foreignkey')
    op.create_foreign_key(None, 'detail', 'college', ['college_id'], ['id'])
    op.drop_column('detail', 'college_details_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('college_details_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'detail', type_='foreignkey')
    op.create_foreign_key('detail_ibfk_1', 'detail', 'college_details', ['college_details_id'], ['id'])
    op.drop_column('detail', 'college_id')
    # ### end Alembic commands ###
