"""removed moderator details

Revision ID: 8b8ded12c7c5
Revises: f89aa57b14ba
Create Date: 2019-02-21 20:40:59.117116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b8ded12c7c5'
down_revision = 'f89aa57b14ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('assigned_to', sa.String(length=256), nullable=True))
    op.add_column('submission', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.drop_column('submission', 'reviewed_by_admin')
    op.drop_column('submission', 'reviewed_by_moderator')
    op.drop_column('submission', 'reviewed_by_admin_at')
    op.drop_column('submission', 'reviewed_by_moderator_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('reviewed_by_moderator_at', mysql.DATETIME(), nullable=True))
    op.add_column('submission', sa.Column('reviewed_by_admin_at', mysql.DATETIME(), nullable=True))
    op.add_column('submission', sa.Column('reviewed_by_moderator', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('submission', sa.Column('reviewed_by_admin', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('submission', 'reviewed_at')
    op.drop_column('submission', 'assigned_to')
    # ### end Alembic commands ###
