"""college scholarship and scholarships needed

Revision ID: 8e6a08d1355c
Revises: 08a453bfc656
Create Date: 2019-03-14 02:19:45.230916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6a08d1355c'
down_revision = '08a453bfc656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships_needed',
    sa.Column('needs_id', sa.Integer(), nullable=True),
    sa.Column('needed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['needed_id'], ['scholarship.id'], ),
    sa.ForeignKeyConstraint(['needs_id'], ['scholarship.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholarships_needed')
    # ### end Alembic commands ###
