"""major schema

Revision ID: 911dde1e5a2b
Revises: 64aee479ac50
Create Date: 2019-03-05 01:18:50.169281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911dde1e5a2b'
down_revision = '64aee479ac50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_name'), 'major', ['name'], unique=True)
    op.create_table('college_major',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college_major')
    op.drop_index(op.f('ix_major_name'), table_name='major')
    op.drop_table('major')
    # ### end Alembic commands ###
