"""users

Revision ID: bddd089de731
Revises: 99376e9288bf
Create Date: 2019-01-28 00:01:23.535915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddd089de731'
down_revision = '99376e9288bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_session', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=256), nullable=True))
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.TEXT(), nullable=True))
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_session')
    # ### end Alembic commands ###
