"""programs requirement

Revision ID: c57b89512e81
Revises: 767a3f6a8185
Create Date: 2019-03-15 20:16:02.001200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57b89512e81'
down_revision = '767a3f6a8185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_requirement',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_requirement_qualification_round',
    sa.Column('program_requirement_id', sa.Integer(), nullable=True),
    sa.Column('qualification_round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_requirement_id'], ['program_requirement.id'], ),
    sa.ForeignKeyConstraint(['qualification_round_id'], ['qualification_round.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_requirement_qualification_round')
    op.drop_table('program_requirement')
    # ### end Alembic commands ###
