"""chosen_college_requirement

Revision ID: ce4ddee0e907
Revises: c57b89512e81
Create Date: 2019-03-20 17:44:15.171523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4ddee0e907'
down_revision = 'c57b89512e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chosen_college_requirement',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chosen_college_requirement')
    # ### end Alembic commands ###
