"""access_token_jti column to refresh_token table

Revision ID: d15cae5ce81c
Revises: 
Create Date: 2019-01-13 16:56:22.424775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15cae5ce81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('room_and_board', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('type_of_institution', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('in_state_tuition', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('out_of_state_tuition', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('religious_affiliation', sa.String(length=256), nullable=True),
    sa.Column('setting', sa.String(length=256), nullable=True),
    sa.Column('number_of_students', sa.Integer(), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_name'), 'major', ['name'], unique=True)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('round_qualification', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=False)
    op.create_table('refresh_token',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('access_token_jti', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_fips_code'), 'state', ['fips_code'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('college_major',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], )
    )
    op.create_table('college_state',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], )
    )
    op.create_table('college_state_blacklist',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], )
    )
    op.create_table('consolidated_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consolidated_city_fips_code'), 'consolidated_city', ['fips_code'], unique=True)
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_county_fips_code'), 'county', ['fips_code'], unique=True)
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_fips_code'), 'place', ['fips_code'], unique=True)
    op.create_table('scholarship',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('act', sa.SmallInteger(), nullable=True),
    sa.Column('sat', sa.SmallInteger(), nullable=True),
    sa.Column('amount', sa.String(length=256), nullable=True),
    sa.Column('amount_expression', sa.String(length=256), nullable=True),
    sa.Column('unweighted_hs_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('legal_status', sa.String(length=256), nullable=True),
    sa.Column('relevant_information', sa.String(length=256), nullable=True),
    sa.Column('graduated_spring_before_scholarship', sa.Boolean(), nullable=True),
    sa.Column('paid_full_time_christian_ministry_parent', sa.Boolean(), nullable=True),
    sa.Column('parents_higher_education', sa.Boolean(), nullable=True),
    sa.Column('siblings_currently_in_scholarship', sa.Boolean(), nullable=True),
    sa.Column('application_needed', sa.Boolean(), nullable=True),
    sa.Column('first_choice_national_merit', sa.Boolean(), nullable=True),
    sa.Column('exclude_from_match', sa.Boolean(), nullable=True),
    sa.Column('group_by', sa.Integer(), nullable=True),
    sa.Column('first_generation_higher_education', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ethnicity', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('college_consolidated_city',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('consolidated_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['consolidated_city_id'], ['consolidated_city.id'], )
    )
    op.create_table('college_consolidated_city_blacklist',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('consolidated_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['consolidated_city_id'], ['consolidated_city.id'], )
    )
    op.create_table('college_county',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], )
    )
    op.create_table('college_county_blacklist',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], )
    )
    op.create_table('college_place',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], )
    )
    op.create_table('college_place_blacklist',
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], )
    )
    op.create_table('scholarship_consolidated_city',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('consolidated_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consolidated_city_id'], ['consolidated_city.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_consolidated_city_blacklist',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('consolidated_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consolidated_city_id'], ['consolidated_city.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_county',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_county_blacklist',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['county.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_place',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_place_blacklist',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_program',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], )
    )
    op.create_table('scholarship_state',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], )
    )
    op.create_table('scholarship_state_blacklist',
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], )
    )
    op.create_table('scholarships_needed',
    sa.Column('needs_id', sa.Integer(), nullable=True),
    sa.Column('needed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['needed_id'], ['scholarship.id'], ),
    sa.ForeignKeyConstraint(['needs_id'], ['scholarship.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholarships_needed')
    op.drop_table('scholarship_state_blacklist')
    op.drop_table('scholarship_state')
    op.drop_table('scholarship_program')
    op.drop_table('scholarship_place_blacklist')
    op.drop_table('scholarship_place')
    op.drop_table('scholarship_county_blacklist')
    op.drop_table('scholarship_county')
    op.drop_table('scholarship_consolidated_city_blacklist')
    op.drop_table('scholarship_consolidated_city')
    op.drop_table('college_place_blacklist')
    op.drop_table('college_place')
    op.drop_table('college_county_blacklist')
    op.drop_table('college_county')
    op.drop_table('college_consolidated_city_blacklist')
    op.drop_table('college_consolidated_city')
    op.drop_table('scholarship')
    op.drop_index(op.f('ix_place_fips_code'), table_name='place')
    op.drop_table('place')
    op.drop_table('picture')
    op.drop_index(op.f('ix_county_fips_code'), table_name='county')
    op.drop_table('county')
    op.drop_index(op.f('ix_consolidated_city_fips_code'), table_name='consolidated_city')
    op.drop_table('consolidated_city')
    op.drop_table('college_state_blacklist')
    op.drop_table('college_state')
    op.drop_table('college_major')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_state_fips_code'), table_name='state')
    op.drop_table('state')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_major_name'), table_name='major')
    op.drop_table('major')
    op.drop_table('college')
    # ### end Alembic commands ###
