"""programs and qualification rounds

Revision ID: e7e3cb7f9f20
Revises: 625933f7b1a1
Create Date: 2019-03-10 21:10:38.760714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e3cb7f9f20'
down_revision = '625933f7b1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=True)
    op.create_table('qualification_round',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_round_name'), 'qualification_round', ['name'], unique=True)
    op.create_table('program_qualification_round',
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('qualification_round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['qualification_round_id'], ['qualification_round.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_qualification_round')
    op.drop_index(op.f('ix_qualification_round_name'), table_name='qualification_round')
    op.drop_table('qualification_round')
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
