"""boolean requirement

Revision ID: eacec28e5f6d
Revises: ce4ddee0e907
Create Date: 2019-03-23 00:40:58.309843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacec28e5f6d'
down_revision = 'ce4ddee0e907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boolean_requirement',
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('required_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], ),
    sa.PrimaryKeyConstraint('scholarship_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boolean_requirement')
    # ### end Alembic commands ###
