"""grade requirement

Revision ID: eecbb9ecebbd
Revises: 504f878c6f61
Create Date: 2019-03-24 21:35:24.351628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eecbb9ecebbd'
down_revision = '504f878c6f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college_grade_requirement_group')
    op.drop_table('scholarship_grade_requirement_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_grade_requirement_group',
    sa.Column('scholarship_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grade_requirement_group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['grade_requirement_group'], ['grade_requirement_group.id'], name='scholarship_grade_requirement_group_ibfk_1'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], name='scholarship_grade_requirement_group_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('college_grade_requirement_group',
    sa.Column('college_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grade_requirement_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], name='college_grade_requirement_group_ibfk_1'),
    sa.ForeignKeyConstraint(['grade_requirement_group_id'], ['grade_requirement_group.id'], name='college_grade_requirement_group_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
