"""submission schema

Revision ID: f89aa57b14ba
Revises: 2d504fef79db
Create Date: 2019-02-13 20:25:46.185730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89aa57b14ba'
down_revision = '2d504fef79db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by_moderator_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_admin_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_moderator', sa.String(length=256), nullable=True),
    sa.Column('reviewed_by_admin', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('college_name', sa.String(length=256), nullable=True),
    sa.Column('submitted_by', sa.String(length=256), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
